hooknows/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('hooknows/', include('hooknowsapp.urls')),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include('hooknowsapp.urls')),
]

hooknowsapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from hooknowsapp import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home, name='home'),
    path('create_report/', views.create_report, name='create_report'),
    path('view_reports/', views.view_reports, name='view_reports'),
    path('report_submited/', views.report_submitted, name='report_submitted'),
    path('one_report/<int:report_id>/', views.one_report, name='one_report'),
    path('view_user_reports/', views.view_user_reports, name='view_user_reports'),
    path('add_admin_note/<int:report_id>/', views.add_admin_note, name='add_admin_note'),
    path('report_resolved/<int:report_id>/', views.report_resolved, name='report_resolved'),
    path('report/<int:report_id>/delete/', views.delete_report, name='delete_report'),
    path('reports/', views.report_list, name='report_list'),
    re_path(r'^search/$', views.report_list, name='search'),
]

hooknowsapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Report(models.Model):
    submission_types = (
        ('new', 'New'),
        ('in_progress', 'In Progress'),
        ('resolved', 'Resolved'),
    )
    ISSUE_TYPES = (
        ('professors', 'Professor'),
        ('teaching_assistant', 'Teaching Assistant'),
        ('homework_assignments', 'Homework Assignment'),
        ('course_logistics', 'Course Logistics'),
        ('tests_exams', 'Test/Exam'),
        ('others', 'Other'),
    )
    issue_type = models.CharField(
        max_length=30, 
        choices=ISSUE_TYPES, 
        default='others',
        verbose_name="Related to"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=60)
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.TextField(default='', max_length=200)
    file = models.FileField(upload_to='reports/', null=True, blank=True)
    submission_status = models.CharField(max_length=30, choices=submission_types, default='New')

 
class AdminNote(models.Model):
    report = models.ForeignKey(Report, related_name='admin_notes', on_delete=models.CASCADE)
    note = models.TextField()


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    report = models.ForeignKey(Report, on_delete=models.CASCADE, blank=True, null=True)
    message = models.TextField(default='', max_length=200)
    read = models.BooleanField(default=False)

hooknowsapp/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):
    file = forms.FileField(required=False)
    issue_type = forms.ChoiceField(
        choices=Report.ISSUE_TYPES, 
        required=False,
        label="Issue Type",
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Describe the details of the issue here. If you chose "Others" in the previous field, please provide more details here.'}),
        required=True,
    )

    class Meta:
        model = Report
        fields = ["title","issue_type", "description", "file" ]  
        exclude = {"created_at"}

hooknowsapp/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User, AnonymousUser
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from .models import Report, AdminNote, Notification
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse
from .forms import ReportForm
from .filters import ReportFilter


def login_view(request):
    if request.user.is_authenticated:
        return redirect('/home')
    else:
        return render(request, 'hooknowsapp/login.html')


def home(request):
    notifications = None
    is_site_admin = False  

    if request.user.is_authenticated:
        is_site_admin = request.user.groups.filter(name='Site Admin').exists()

        if not is_site_admin and not request.user.is_anonymous:
            notifications = Notification.objects.filter(user=request.user, read=False)

    return render(request, 'hooknowsapp/homepage.html', {
        'notifications': notifications,
        'is_site_admin': is_site_admin 
    })

def logout_view(request):
    logout(request)
    return redirect("/")


def create_report(request):
    if request.method == "POST":
        form = ReportForm(request.POST, request.FILES)
        if form.is_valid():
            if(request.user.is_anonymous):
                form.save()
                return render(request, 'hooknowsapp/report_submitted.html')
            else:
                report = form.save(commit=False)
                report.user = request.user
                report.save()
                return render(request, 'hooknowsapp/report_submitted.html')
    else:
        form = ReportForm()

    return render(request, 'hooknowsapp/create_report.html', {"form" : form})


def view_reports(request):
    reports = Report.objects.all()
    is_site_admin = False
    is_site_admin = request.user.groups.filter(name='Site Admin').exists()

    return render(request, 'hooknowsapp/view_reports.html', {'is_site_admin': is_site_admin,'reports': reports})


def view_user_reports(request):
    user_id = request.user
    reports = Report.objects.filter(user_id=user_id)
    is_site_admin = False
    is_site_admin = request.user.groups.filter(name='Site Admin').exists()
    return render(request, 'hooknowsapp/view_reports.html', {'is_site_admin': is_site_admin, 'reports': reports})

def one_report(request, report_id):
    report = get_object_or_404(Report, pk=report_id)
    is_site_admin = False
    is_site_admin = request.user.groups.filter(name='Site Admin').exists()

    if is_site_admin:
        if report.submission_status == "New":
            report.submission_status = "In Progress"
            report.save()
            Notification.objects.create(user=report.user, report=report,
                                        message=f"Report {report_id} status has changed.")
    if not is_site_admin and not request.user.is_anonymous:
        notif = Notification.objects.filter(user=request.user, report=report, read=False)
        notif.update(read=True)
    return render(request, 'hooknowsapp/one_report.html', {'is_site_admin': is_site_admin, 'report': report})

@login_required
def report_resolved(request, report_id):
    report = get_object_or_404(Report, pk=report_id)
    is_site_admin = False
    is_site_admin = request.user.groups.filter(name='Site Admin').exists()
    if is_site_admin:
        if report.submission_status == "Resolved":
            report.submission_status = "In Progress"
            Notification.objects.create(user=report.user, report=report,
                                        message=f"Report {report_id} status has changed.")
        else:
            report.submission_status = "Resolved"
            Notification.objects.create(user=report.user, report=report,
                                        message=f"Report {report_id} has been resolved.")
        report.save()
    else:
        return HttpResponseForbidden("You do not have permission to perform this action.")
    return render(request, 'hooknowsapp/one_report.html', {'is_site_admin': is_site_admin, 'report': report})


def report_submitted(request):
    return render(request, 'hooknowsapp/report_submitted.html')

def add_admin_note(request, report_id):
    is_site_admin = False
    is_site_admin = request.user.groups.filter(name='Site Admin').exists()
    if request.method == "POST" and is_site_admin:
        report = get_object_or_404(Report, pk=report_id)
        note_content = request.POST.get('note', '')
        if note_content.strip():
            AdminNote.objects.create(report=report, note=note_content)
        return HttpResponseRedirect(reverse('one_report', args=[report_id]))
    else:
        return HttpResponseRedirect(reverse('home'))


@login_required
def delete_report(request, report_id):
    is_site_admin = False
    is_site_admin = request.user.groups.filter(name='Site Admin').exists()
    report = get_object_or_404(Report, id=report_id)
    if request.user == report.user and not is_site_admin:
        report.delete()
        return redirect('view_user_reports')
    else:
        return redirect('view_user_reports')

def report_list(request):
    reports = Report.objects.filter(user=request.user)
    report_filter = ReportFilter(request.GET, queryset=reports)
    filtered_reports = reports.order_by('created_at')
    is_site_admin = request.user.groups.filter(name='Site Admin').exists()

    if is_site_admin:
        reports = Report.objects.all()
        report_filter = ReportFilter(request.GET, queryset=reports)

    if 'search' in request.GET:
        title_search = request.GET.get('title')
        if title_search:
            filtered_reports = report_filter.qs
        else:
            return render(request, 'hooknowsapp/view_reports.html', {
                'is_site_admin': is_site_admin,
                'filter': report_filter,
                'reports': reports,  
            })

    return render(request, 'hooknowsapp/view_reports.html', {
        'is_site_admin': is_site_admin,
        'filter': report_filter,
        'reports': filtered_reports,
    })

hooknowsapp/templates/hooknowsapp/create_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Report</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body, html {
            margin: 0;
            padding: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f5f5f5;
        }

        .navbar-custom {
            background-color: #0056b3;
            padding: 0.5rem 1rem;
        }

        .navbar-custom .navbar-brand, .navbar-custom .nav-link {
            color: #ffffff;
        }

        .container {
            max-width: 600px;
            margin: 2rem auto;
            padding: 2rem;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        h1 {
            color: #333;
            font-size: 1.75rem;
            margin-bottom: 1.5rem;
            text-align: center;
        }

        label {
            display: block;
            margin-bottom: .5rem;
            color: #555;
        }

        input, textarea, .btn-custom, select{
            width: 100%;
            padding: 0.75rem;
            margin-bottom: 1rem;
            border-radius: 5px;
            border: 1px solid #ddd;
            box-sizing: border-box;
        }

        .btn-custom {
            background-color: #0056b3;
            color: #fff;
            text-transform: uppercase;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .btn-custom:hover {
            background-color: #004299;
        }

    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-custom">
        <a class="navbar-brand" href="#">Campus-Confide</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Homepage</a>
            </li>
            <li class="nav-item">
                {% if not user.is_anonymous %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'view_user_reports'%}">My Reports</a>
                </li>
                {% endif %}
            </li>
        </ul>
    </nav>

    <div class="container">
        <h1>File a Report</h1>
        <form action="{% url 'create_report' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-custom">Submit Report</button>
        </form>
    </div>
{% include 'hooknowsapp/footer.html' %}
</body>
</html>

hooknowsapp/templates/hooknowsapp/footer.html
<footer>
    <style>
        footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            color: #808080;
            font-size: 11px;
        }
    </style>
    <p>
        This is a UVA CS 3240 University Project.
        The data submitted here will not be monitored and no real data should be submitted.
    </p>
</footer>

hooknowsapp/templates/hooknowsapp/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body, html {
            margin: 0;
            padding: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .navbar-custom {
            background-color: #0056b3;
            padding: 0.5rem 1rem;
        }

        .navbar-custom .navbar-brand, .navbar-custom .nav-link {
            color: #ffffff;
        }

        .container {
            padding-top: 2rem;
        }

        h2 {
            color: #333;
            margin-bottom: 20px;
        }

        .alert {
            margin-bottom: 20px;
        }

        .btn-primary, .btn-secondary {
            margin-right: 10px;
        }

        .btn-primary {
            background-color: #0056b3;
            border-color: #004299;
        }

        .btn-secondary {
            background-color: #6c757d;
            border-color: #545b62;
        }
        .max-size {
            max-width: 800px;
            margin: auto;
        }

        @media (max-width: 768px) {
            .max-size {
                max-width: 400px;
            }
        }
        


    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-custom">
        <a class="navbar-brand" href="#">Campus-Confide</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            </li>
        </ul>
    </nav>

    <div class="container max-size">
        {% if is_site_admin %}
            <h2>Hello, Admin {{ user.first_name }}!</h2>
            <div class="mt-3 mb-3">Manage incoming reports here.</div>
            <p class="mt-3 mb-3">Explore and manage academic-related student issues with ease. Update statuses, and post resolutions to ensure a smooth educational experience.</p>
        {% else %}
            {% if user.is_anonymous %}
                <h2>Welcome, Anonymous User!</h2>
                <div class="mt-3 mb-3">Encountering an issue? Let us know!</div>
                <p class="mt-3 mb-3">Your academic journey should be seamless. If you stumble upon any issues, have feedback, or suggestions, this is the place to share them. Your input is invaluable in enhancing the academic experience for everyone.</p>
            {% elif user.is_staff %}
                <h2>Welcome, {{ request.user.username }} !</h2>
                <div class="mt-3 mb-3">Encountering an issue? Let us know!</div>
                <p class="mt-3 mb-3">Your academic journey should be seamless. If you stumble upon any issues, have feedback, or suggestions, this is the place to share them. Your input is invaluable in enhancing the academic experience for everyone.</p>
            {% else %}
                <h2>Welcome, {{ user.first_name }}!</h2>
                <div class="mt-3 mb-3">Encountering an issue? Let us know!</div>
                <p class="mt-3 mb-3">Your academic journey should be seamless. If you stumble upon any issues, have feedback, or suggestions, this is the place to share them. Your input is invaluable in enhancing the academic experience for everyone.</p>
            {% endif %}
        {% endif %}

        {% if notifications %}
            <div class="alert alert-success" role="alert">
                <h4 class="alert-heading">Report Update!</h4>
                {% for notification in notifications|slice:":5" %}
                    <p>{{ notification.message }}</p>
                {% endfor %}
                <hr>
                <p class="mb-0">View your reports to see any updates.</p>
            </div>
        {% endif %}

        {% if user.is_anonymous %}
            <a class="btn btn-primary" href="{% url 'create_report' %}" role="button">Create Report</a>
        {% else %}
            {% if is_site_admin %}
                <a class="btn btn-primary" href="{% url 'view_reports' %}" role="button">View Reports</a>
            {% else %}
                <div class="small-container">
                    <a class="btn btn-primary" href="{% url 'create_report' %}" role="button">Create Report</a>
                    <a class="btn btn-secondary" href="{% url 'view_user_reports' %}" role="button">View User Reports</a>
                </div>
            {% endif %}
        {% endif %}
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
{% include 'hooknowsapp/footer.html' %}
</body>
</html>

hooknowsapp/templates/hooknowsapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Google Sign In</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f5f5f5;
        }
        .card {
            border-radius: 0.5rem;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .btn {
            border-radius: 0.375rem;
        }
        .btn-danger {
            background-color: #ea4335;
            border-color: #ea4335;
        }
        .btn-danger:hover {
            background-color: #d93025;
            border-color: #d93025;
        }
        .btn-primary {
            background-color: #1a73e8;
            border-color: #1a73e8;
        }
        .btn-primary:hover {
            background-color: #1358b4;
            border-color: #1358b4;
        }
        h2 {
            font-weight: 600;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card my-5">
                    <div class="card-body">
                        {% load socialaccount %}
                        <h2 class="text-center mb-4">Campus-Confide</h2>
                        <div class="text-center mb-3">
                            <a href="/accounts/google/login/?process=login&next=/" class="btn btn-danger px-4">Login With Google</a>
                            <a href="{% url 'home' %}" class="btn btn-primary px-4 ml-2">Continue Anonymously</a>
                        </div>

                        {% if user.is_authenticated %}
                        <h2 class="text-center mb-4">Welcome {{ user.username }}</h2>
                        <div class="text-center mb-3">
                            <a href="{% url 'logout' %}" class="btn btn-secondary">Logout</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    {% include 'hooknowsapp/footer.html' %}
</body>
</html>

hooknowsapp/templates/hooknowsapp/one_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report Details</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body, html {
            margin: 0;
            padding: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f4f4f4;
        }

        .navbar-custom {
            background-color: #0056b3;
            color: #ffffff;
        }

        .navbar-custom .navbar-brand, .navbar-custom .nav-link {
            color: #ffffff;
        }

        .reports-container {
            padding: 20px;
            max-width: 800px;
            margin: auto;
        }

        .report {
            background-color: #ffffff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }

        .report-title, .report-description, .submission-type, .date {
            margin-bottom: 15px;
        }

        .report-title {
            color: #0056b3;
            font-size: 24px;
            margin-bottom: 20px;
        }

        .report-description {
            word-wrap: break-word;
            overflow-wrap: break-word;
        }

        .btn-primary {
            background-color: #0056b3;
            border-color: #004299;
        }

        .admin-note-form textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            border: 1px solid #ddd;
        }

        .admin-note-form input[type=submit] {
            background-color: #0056b3;
            color: #ffffff;
            padding: 10px 20px;
            border-radius: 5px;
            border: none;
            cursor: pointer;
        }

        a, a:hover {
            text-decoration: none;
            color: #0056b3;
        }
        .admin-note {
            background-color: #f9f9f9;
            padding: 20px;
            margin-top: 10px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);

        }
        .delete-report {
            margin-top: 20px;
            width: 100%; /* Take the full width of the parent */
            display: flex;
            justify-content: center; /* Center the button horizontally */
        }

    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-custom">
        <a class="navbar-brand" href="#">Campus-Confide</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Homepage</a>
            </li>
            <li class="nav-item">
                {% if not is_site_admin %}
                    <a class="nav-link" href="{% url 'view_user_reports' %}">Return</a>
                {% else %}
                    <a class="nav-link" href="{% url 'view_reports' %}">Return</a>
                {% endif %}
            </li>
        </ul>
    </nav>

    <div class="reports-container">
        <div class="report">
            <h1 class="report-title">Report Title: {{ report.title }}</h1>
            <p class="date">Created on: {{ report.created_at|date:"F d, Y H:i" }}</p>
            <p class="date">Report Type: {{ report.get_issue_type_display }}</p>
            <p class="report-description">Description: {{ report.description }}</p>
            <p class="submission-type">Status: {{ report.submission_status }}</p>
            {% if report.file %}
                <p><a href="{{ report.file.url }}" target="_blank">View File</a></p>
            {% endif %}
        </div>
        <div class="admin-note">
            <p>Admin Notes:</p>
            {% for note in report.admin_notes.all %}
                <div class="note">
                    <p>{{ note.created_at|date:"F d, Y H:i" }} - {{ note.note }}</p>
                </div>
            {% empty %}
                <p>No notes from admin.</p>
            {% endfor %}
        </div>
        
        {% if report.user and is_site_admin %}
            <div class="resolved">
                <form action="{% url 'report_resolved' report.id %}" method="post">
                {% csrf_token %}
                    <button type="submit" class="btn btn-primary mt-4 mb-3">Resolved</button>
                </form>
            </div>
            <div class="admin-note-form">
                <h2>Add Note:</h2>
                <form action="{% url 'add_admin_note' report.id %}" method="post">
                    {% csrf_token %}
                    <textarea name="note" rows="4" placeholder="Enter your note here..."></textarea>
                    <br>
                    <input type="submit" value="Submit Note">
                </form>
            </div>
    </div>
        {% endif %}
        {% if report.user == user and not is_site_admin %}
                <div class="delete-report">
                    <a class="btn btn-danger" href="#" data-toggle="modal" data-target="#exampleModal">Delete</a>
                    <!-- <a href="{% url 'delete_report' report.id %}" class="btn btn-danger">Delete Report</a> -->
                </div>
        {% endif %}
        

{% include 'hooknowsapp/footer.html' %}

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <!-- <h5 class="modal-title" id="exampleModalLabel"></h5> -->
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Are you sure you want to delete this report?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <a class="btn btn-danger" href="{% url 'delete_report' report.id %}">Delete</a>
          </div>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


</body>
</html>

hooknowsapp/templates/hooknowsapp/view_reports.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports List</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body, html {
            margin: 0;
            padding: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f4f4f4;
        }

        .navbar-custom {
            background-color: #0056b3;
            color: #ffffff;
        }

        .navbar-custom .navbar-brand, .navbar-custom .nav-link {
            color: #ffffff;
        }

        .filter {
            align-items: center;
        }

        .reports-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 20px;
            padding: 20px;
        }

        .report {
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            padding: 20px;
            width: 300px;
            transition: transform 0.2s;
        }

        .report:hover {
            transform: scale(1.05);
        }

        .report-title {
            color: #333;
            font-size: 18px;
        }

        .submission-type {
            font-weight: bold;
            color: #0056b3;
        }

        .admin-notes {
            background-color: #f8f9fa;
            padding: 10px;
            margin-top: 10px;
            border-radius: 5px;
        }

        .note p {
            font-size: 14px;
        }

        .btn-primary {
            background-color: #0056b3;
            border-color: #004299;
        }

        a, a:hover {
            text-decoration: none;
            color: #0056b3;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-custom">
        <a class="navbar-brand" href="#">Campus-Confide</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Homepage</a>
            </li>
            <li class="nav-item">
                {% if not is_site_admin %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_report'%}">Create Report</a>
                </li>
                {% endif %}
            </li>
        </ul>
    </nav>

    <div class="reports-container">
        {% block content %}
        <div class="filter">
            <div class="d-flex justify-content-center align-items-end mt-4">
                <form method="get" action="{% url 'report_list' %}" class="d-flex">
                    <h4 class="mb-0 mr-2">Filter</h4>
                    <input type="text" name="title" value="{{ request.GET.title }}" placeholder="Search from title" class="mr-2">
                    <button class="btn btn-primary mr-2" type="submit" name="search">Search</button>
                </form>
                {% if is_site_admin %}
                    <a class="btn btn-outline-primary" href="{% url 'view_reports' %}">Reset</a>
                {%else%}
                    <a class="btn btn-outline-primary" href="{% url 'report_list' %}">Reset</a>
                {% endif %}

            </div>
        </div>
            
    </div>

    <div class="reports-container">
        {% for report in reports %}
            <div class="report">    
                <h2 class="report-title">Report {{ report.id }}: {{ report.title }}</h2>
                <p class="mb-2">Created on: {{ report.created_at|date:"F d, Y H:i" }}</p>
                <p>Report Type: {{ report.get_issue_type_display }}</p>
                <p class="submission-type">Report Status: {{ report.submission_status }}</p>
                <a href="{% url 'one_report' report.id %}">View Report Details</a>
            </div>
        {% endfor %}
        {% endblock %}
    </div>
{% include 'hooknowsapp/footer.html' %}
</body>
</html>